max_batch_size = 352
clean_rollout_path = true

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
max_model_len = 8192

[data]
name = "PrimeIntellect/INTELLECT-2-only-math"

[data.difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.4
max_solve_rate = 0.9

[parallel]
dp = 6

[rl]
ckpt_path = "checkpoints"
clean_ckpt_path = true
