max_batch_size = 256
clean_rollout_path = true

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
max_model_len = 16000

[data]
name = "PrimeIntellect/INTELLECT-2-RL-Dataset"

[data.difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.0
max_solve_rate = 0.7

[parallel]
tp = "auto"

[sampling]
n = 32

[rl]
ckpt_path = "checkpoints"
clean_ckpt_path = true