max_batch_size = 256
clean_rollout_path = true

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
max_model_len = 2048

[data]
name = "kalomaze/fwedu-unscramble-mix-it1"

[parallel]
dp = 4

[rl]
ckpt_path = "checkpoints"
clean_ckpt_path = true