max_steps = 50
max_batch_size = 128
clean_rollout_path = true

[model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"
max_model_len = 128

[data]
name = "mikasenghaas/reverse_text_dataset_debug_50_seq_len"

[rl]
ckpt_path = "checkpoints"
clean_ckpt_path = true