project = "math-ablation"

collate_mode = "packing"

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

[train]
micro_bs = 1 # change to 8 for H200
reshard_after_forward = true

[data]
seq_length = 8192
path = "rollouts"

[optim]
batch_size = 2048
step_per_rollout = 1


[optim.optim]
lr = 1e-6

[ckpt]
rollout_path = "checkpoints"
clean_rollout_path = true