name_model = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
batch_size = 1
rollout_path = "outputs"
output_path = "data_rollout"
max_model_len = 2048
dataset = "justus27/math-hendrycks-genesys-format"

[sampling]
n = 4



