rollout_path = "/data"
rl = "None"
use_tqdm = true
syn2 = true
max_batch_size = 256

[toploc]
enable_toploc1 = true
enable_toploc2 = true

[parallel]
tp = "auto"

[parallel.pp]
connection_num_retries = 100

[rewards]
compute_reward = false