max_steps = 5
rl = "None"
use_tqdm = true
syn2 = true

[toploc]
enable_toploc1 = true
enable_toploc2 = true

[model]
name = "Qwen/Qwen3-0.6B"
max_model_len = 8192

[monitor.file]
path = "monitor.jsonl"

[rewards]
compute_reward = false