wandb = false
collate_mode = "padding"
stop_after_steps = 2

[model]
name = "Qwen/Qwen3-0.6B"

[grpo]
kl_coef = 0.02

[train]
micro_bs = 1

[optim]
batch_size = 2

[data]
fake = true
seq_length = 128
timeout = 1