project = "intellect-2"
collate_mode = "packing"

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"

[train]
micro_bs = 1
reshard_after_forward = true
ac_ckpt = true

[data]
seq_length = 16000
ignore_zero_advantages = true
path = "rollouts"

[optim]
batch_size = 512
step_per_rollout = 8
grad_norm_clip = 0.1


[optim.optim]
lr = 3e-7