project = "math-debug"

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

[train]
micro_bs = 4 # change to 8 for H200
reshard_after_forward = true

[optim]
batch_size = 128
step_per_rollout = 4

[optim.optim]
lr = 1e-6



[data]
path = "rollouts"
seq_length = 2048

[ckpt]
rollout_path = "checkpoints"
clean_rollout_path = true