project = "unscramble-debug"

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

[train]
micro_bs = 2 # change to 8 for H200
reshard_after_forward = true

[optim]
batch_size = 32
step_per_rollout = 4
grad_norm_clip = 0.00001

[optim.optim]
lr = 4e-5

[data]
path = "rollouts"
seq_length = 4096

[ckpt]
rollout_path = "checkpoints"