batch_size = 8
micro_batch_size = 8
rollouts_per_prompt = 8
seq_len = 12288
mask_truncated_completions = true

[model]
name = "Qwen/Qwen3-4B"

[environment]
id = "swe-rl"

[sampling]
max_tokens = 4096
temperature = 0.6

[monitor.wandb]

[monitor.wandb.log_samples]
interval = 5
num_samples = 2
